title: "Phffff=blog==="
description: ""
show_downloads: false
exclude: ["mold.yaml"]
blog_subtitle: "programming languages // distributed systems // music"

plugins:
  - jekyll-feed

top_links:
  - label: music
    url: https://phfilip.com/music
  - label: bandcamp
    url: https://philipdexter.bandcamp.com
  - label: github
    url: https://github.com/philipdexter
  - label: cv
    url: https://phfilip.com/cv
  - label: misc.
    items:
      - label: vibe6 visualizer
        url: https://phfilip.com/music/vibe6-visualizer.html
      - label: skigame
        url: https://phfilip.com/skigame
      - label: build-a-lang
        url: https://phfilip.com/build-a-lang/
